admin_app/urls.py


from django.urls import path
from .import views

app_name = 'admin_app'

urlpatterns = [
    path('',views.index, name="admin_index"),
    path('admin/',views.dashboard, name="admin"),
    path('user_profile/',views.user_profile, name="user_profile"),
    path('register/',views.register, name="register"),
    path('login/',views.login, name="login"),
]

mwala_app/urls.py


from django.urls import path
from .import views

app_name = 'mwala_app'

urlpatterns = [
    path('',views.homePage, name="index"),
    path('principal-detail/', views.principalDetail, name='principal_detail'),
    path('courses/<slug:level>/', views.courseLevelView, name='course_level'),
    path('notices/', views.all_notices, name='all_notices'),
    path('bog/', views.Bog, name='bog'),
    path('Brochure/', views.Brochure, name='Brochure'),
    path('JobsVacancies/', views.all_jobsVacancies, name='JobsVacancies'),
    path('tenders/', views.all_tenders, name='tenders'),
    path('gallery', views.collageGallery, name='gallery'),
    path('get_images_for_carousel/', views.get_images_for_carousel, name='get_images_for_carousel'),
    path('newsEvents/', views.newsEvents, name='newsEvents'),
    path('news_details/<int:news_id>/', views.news_details, name='news_details'),
    path('history/',views.historyPage, name="history"),
    path('adminstration/',views.adminstrationPage, name="adminstration"),
    path('administration/<int:id>/', views.adminstrationDetails, name='adminstrationDetails'),
    path('departments/<int:department_id>/', views.department_details, name='department_details'),
    path('support_department/<int:support_department_id>/', views.supporting_department_details, name='support_department'),
    path('allCourses/',views.allCourses, name="allCourses"),
    path('departments/',views.allDepartments, name="departments"),
    path('departments/<int:department_id>/', views.department_details, name='department_details'),
    path('contactUs/',views.contact_view, name="contactUs"),
    path('contacts/', views.contact_list_view, name='contact_list'),
    path('feeStructure/',views.feeStructure, name="feeStructure"),
    path('clearanceForm/',views.clearanceForm, name="clearanceForm"),
    path('courseTransferForm/',views.courseTransferForm, name="courseTransferForm"),
    path('feeRefundForm/',views.feeRefundForm, name="feeRefundForm"),
    path('serviceCharter/',views.serviceCharter, name="serviceCharter"),
    path('mwalaServices', views.service, name="mwalaServices"),
    path('examinations', views.examinations, name="examinations"),
    path('feedBack/',views.feedback_view, name="feedBack"),
    path('feedback-list/', views.feedback_list_view, name='feedback_list'),
    path('studentAffairs/<int:student_affairs_id>/', views.studentAffairs, name='studentAffairs'),
    path('govnt_scholar/',views.govnt_scholar, name="govnt_scholar"),
    path('applicationForm/',views.applicationForm, name="applicationForm"),
    path('onlineApplication/',views.admission_application_view, name="onlineApplication"),
    path('applicationPdf/',views.applicationPdf, name="applicationPdf"),
    path('admissions/', views.admission_applications, name='admission_applications'),
    path('get_course_levels/<int:course_id>/', views.get_course_levels, name='get_course_levels'),
    path('details/<int:id>/', views.adminstrationDetails, name='details'),
    path('search/', views.search_view, name='search'),
    path('get-counties/', views.get_counties, name='get_counties'),
    path('get-courses/<int:department_id>/', views.get_courses, name='get_courses'),
]

proj_mwalatvc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mwala_app.urls', namespace='mwala_app')),
    path('admin/', include('admin_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/trash/trash.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="admissionsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Admissions
    </a>
    <ul class="dropdown-menu" aria-labelledby="admissionsDropdown">
        <li class="dropdown-submenu">
            <a class="dropdown-item" href="#">
                Our Courses
                <i class="bi bi-chevron-right toggle-dropdown text-blue"></i>
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'mwala_app:allCourses' %}">All Courses</a></li>
                <li><a class="dropdown-item" href="{% url 'mwala_app:diploma' level='diploma' %}
                    ">Level 6 (Diploma)</a></li>
                <li><a class="dropdown-item" href="{% url 'mwala_app:certificate' level='certificate' %}">Level 5 (Certificate)</a></li>
                <li><a class="dropdown-item" href="{% url 'mwala_app:artisan' level='artisan' %}">Level 4 (Artisan)</a></li>
                <li><a class="dropdown-item" href="{% url 'mwala_app:nitaCourses' level='NITA' %}">NITA Courses</a></li>
                <li><a class="dropdown-item" href="{% url 'mwala_app:accounting' level='Accounting' %}">Accounting Courses</a></li>
                <li><a class="dropdown-item" href="{% url 'mwala_app:shortCourses' level='Short courses' %}">Level 3 (Short Courses)</a></li>
            </ul>
        </li>
        <li><a class="dropdown-item" href="{% url 'mwala_app:onlineApplication' %}">Online Application</a></li>
        <li><a class="dropdown-item" href="{% url 'mwala_app:applicationForm' %}">Application Instructions</a></li>
        <li><a class="dropdown-item" href="{% url 'mwala_app:applicationPdf' %}">Download Application Form</a></li>
        <li><a class="dropdown-item" href="{% url 'mwala_app:feeStructure' %}">Fee Structure</a></li>
    </ul>
</li>


<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="courses\departments\all_department.html" id="coursesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Academics
    </a>
    <ul class="dropdown-menu" aria-labelledby="coursesDropdown">
        <li><a class="dropdown-item" href="{% url 'mwala_app:departments' %}">Academic Departments</a></li>
        <li><a class="dropdown-item" href="{% url 'mwala_app:govnt_scholar' %}">Government Scholarship</a></li>
        <li class="dropdown-submenu">
          <a class="dropdown-item" href="#">Support Departments 
              <i class="bi bi-chevron-right toggle-dropdown text-blue"></i>
          </a>
          <ul class="dropdown-menu">
              {% for supporting_department in supporting_departments %}
                  <li><a class="dropdown-item" href="{% url 'mwala_app:support_department' support_department_id=supporting_department.id %}">{{ supporting_department.title }}</a></li>
              {% empty %}
                  <li><a class="dropdown-item" href="#">No departments available</a></li>
              {% endfor %}
          </ul>
      </li>
      
      
    </ul>
</li>


<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="resourcesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Media
    </a>
    <ul class="dropdown-menu" aria-labelledby="resourcesDropdown">
        <li><a class="dropdown-item" href="{% url 'mwala_app:newsEvents' %}">News & Events</a></li>
        <li><a class="dropdown-item" href="{% url 'mwala_app:JobsVacancies' %}">Jobs & Vacancies</a></li>
        <li><a class="dropdown-item" href="{% url 'mwala_app:gallery' %}">Photo Gallery</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="resourcesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Student Affairs
  </a>
  <ul  class="dropdown-menu" aria-labelledby="resourcesDropdown">
    {% for student_affair in all_student_affairs %}
        <li>
            <a class="dropdown-item" href="{% url 'mwala_app:studentAffairs' student_affairs_id=student_affair.id %}">
                {{ student_affair.title }}
            </a>
        </li>
    {% empty %}
        <li>No affairs available</li>
    {% endfor %}
</ul>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="coursesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
   Contact Us
  </a>
  <ul class="dropdown-menu" aria-labelledby="coursesDropdown">
      <li><a class="dropdown-item" href="{% url 'mwala_app:contactUs' %}">Contact Details</a></li>
      <li><a class="dropdown-item" href="{% url 'mwala_app:feedBack' %}">Complaints</a></li>
      
  </ul>
</li>




<li class="nav-item dropdown downloads position-static">
    <a 
        class="nav-link dropdown-toggle" 
        href="#" 
        id="downloadsDropdown" 
        role="button" 
        data-bs-toggle="dropdown" 
        aria-expanded="false">
        Downloads
    </a>
    <div class="dropdown-menu custom-dropdown">
        <div class="container py-3">
            <div class="row">
                <!-- Tenders Section -->
                <div class="col-12">
                    <h6 class="dropdown-header">Tenders</h6>
                    <a class="dropdown-item" href="#">List Of Prequalified Suppliers</a>
                    <a class="dropdown-item" href="#">Provision Of Catering</a>
                </div>
                <!-- Jobs Section -->
                <div class="col-12">
                    <h6 class="dropdown-header">Jobs & Vacancies</h6>
                    <a class="dropdown-item" href="{% url 'mwala_app:JobsVacancies' %}">Jobs & Vacancies</a>
                </div>
                <!-- Students Downloads Section -->
                <div class="col-12">
                    <h6 class="dropdown-header">Students Downloads</h6>
                    <a class="dropdown-item" href="#">Students Rules & Regulations</a>
                    <a class="dropdown-item" href="{% url 'mwala_app:feeStructure' %}">Fee Structure</a>
                    <a class="dropdown-item" href="#">Teaching Practice Form</a>
                    <a class="dropdown-item" href="#">All Forms</a>
                </div>
            </div>
        </div>
    </div>
</li>
<style>


.nav-item.download .dropdown-menu {
    position: absolute;
    top: 70%; /* Position just below the parent item */
    left: 950px; /* Align with the left margin */
    right: 20px; /* Align with the right margin */
    margin: 0;
    padding: 0;
    z-index: 1000; /* Ensure dropdown is on top */
    display: none; /* Initially hide */
}

</style>